version: "3"

services:

  #Nginx webserver
  webserver:
    container_name: webserver
    tty: true
    restart: unless-stopped
    build:
      context: ./
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  # Frontend
  frontend:
    container_name: frontend
    tty: true
    restart: unless-stopped
    build:
      context: ./
      dockerfile: .docker/frontend/Dockerfile
    networks:
      - app-network

  # Backend
  laravel:
    container_name: laravel
    tty: true
    restart: unless-stopped
    build:
      context: ./
      dockerfile: .docker/laravel/Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_SESSION: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      PHP_IDE_CONFIG: 'serverName=laravel'
    depends_on:
      - db
      - redis
      - clickhouse
    networks:
      - app-network

  # DB service (MySQL)
  db:
    container_name: db
    #platform: linux/x86_64 uncomment for MacBook M1
    build:
      context: ./
      dockerfile: .docker/mysql/Dockerfile
    ports:
      - "3308:3308"
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_TCP_PORT: '${DB_PORT}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - app-network

  # ClickHouse service
  clickhouse:
    build:
      context: ./
      dockerfile: .docker/clickhouse/Dockerfile
    container_name: clickhouse
    ports:
      - "8123:8123" # Порт для HTTP-интерфейса ClickHouse
      - "9000:9000" # Порт для TCP-интерфейса ClickHouse
    environment:
      CLICKHOUSE_ADMIN_USER: '${CLICKHOUSE_ADMIN_USER}'
      CLICKHOUSE_ADMIN_PASSWORD: '${CLICKHOUSE_ADMIN_PASSWORD}'
    networks:
      - app-network

  # Mailhog service for work with smtp on localhost
  mailhog:
    container_name: mailhog
    build:
      context: ./
      dockerfile: .docker/mailhog/Dockerfile
    logging:
      driver: 'none'
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui
    networks:
      - app-network

  redis:
    container_name: redis
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

#Docker networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
  redis_data:
    driver: local
