name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        run:
          cd /var/www/parts.sotrans.ru/ &&
          git pull &&
          composer install --optimize-autoloader --no-dev &&
          npm install --frozen-lockfile &&
          npm run prod &&
          php artisan migrate --force &&
          php artisan db:seed --force &&
          php artisan optimize:clear
